apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: myapp
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default

  source:
    repoURL: https://github.com/Nifemi-Stephen/devops-website.git
    targetRevision: HEAD
    path: helm

  destination:
    server: https://kubernetes.default.svc
    namespace: app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
